header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: localization
transform:
  rotation:
    x: 0
    y: 0
    z: 1
    w: 0
  translation:
    x: 0.3
    y: -1.04
    z: 0
child_frame_id: sonic10
